 import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import TanstackQueryProvider from "@/components/custom/tanstack-query-provider";
import AuthQueryProvider from "@/components/custom/auth-query-provider";
import ThemeProvider from "@/components/custom/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackQueryProvider>
          <AuthQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="container mx-auto flex min-h-screen flex-col">
                <TooltipProvider>{children}</TooltipProvider>
                <Toaster position="top-center" />
                <ReactQueryDevtools initialIsOpen={false} />
              </main>
            </ThemeProvider>
          </AuthQueryProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
